// Use this file to store all the multisigs contract addresses
// in only one place - delete or add a new chain/role depending on your deployment
export const multisigs: Record<string, Record<string, string>> = {
  mainnet: {
    PAUSER_ROLE: "YOUR-MAINNET-PAUSER-ROLE-MULTISIG",
    MINTER_ROLE: "YOUR-MAINNET-MINTER-ROLE-MULTISIG",
    UPGRADER_ROLE: "YOUR-MAINNET-UPGRADER-MINTER-ROLE-MULTISIG",
    DEFAULT_ADMIN_ROLE: "YOUR-MAINNET-ADMIN-ROLE-MULTISIG",
  },
  polygon: {
    PAUSER_ROLE: "YOUR-POLYGON-PAUSER-ROLE-MULTISIG",
    MINTER_ROLE: "YOUR-POLYGON-MINTER-ROLE-MULTISIG",
    UPGRADER_ROLE: "YOUR-POLYGON-UPGRADER-MINTER-ROLE-MULTISIG",
    DEFAULT_ADMIN_ROLE: "YOUR-POLYGON-ADMIN-ROLE-MULTISIG",
  },
  sepolia: {
    PAUSER_ROLE: "YOUR-SEPOLIA-PAUSER-ROLE-MULTISIG",
    MINTER_ROLE: "YOUR-SEPOLIA-MINTER-ROLE-MULTISIG",
    UPGRADER_ROLE: "YOUR-SEPOLIA-UPGRADER-MINTER-ROLE-MULTISIG",
    DEFAULT_ADMIN_ROLE: "YOUR-SEPOLIA-ADMIN-ROLE-MULTISIG",
  },
  goerli: {
    PAUSER_ROLE: "YOUR-GOERLI-PAUSER-ROLE-MULTISIG",
    MINTER_ROLE: "YOUR-GOERLI-MINTER-ROLE-MULTISIG",
    UPGRADER_ROLE: "YOUR-GOERLI-UPGRADER-MINTER-ROLE-MULTISIG",
    DEFAULT_ADMIN_ROLE: "YOUR-GOERLI-ADMIN-ROLE-MULTISIG",
  },
  mumbai: {
    PAUSER_ROLE: "YOUR-MUMBAI-PAUSER-ROLE-MULTISIG",
    MINTER_ROLE: "YOUR-MUMBAI-MINTER-ROLE-MULTISIG",
    UPGRADER_ROLE: "YOUR-MUMBAI-UPGRADER-MINTER-ROLE-MULTISIG",
    DEFAULT_ADMIN_ROLE: "YOUR-MUMBAI-ADMIN-ROLE-MULTISIG",
  },
};
